spring.application.name=job-portal-backend
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=job_portal
spring.data.mongodb.auto-index-creation=true


USER_FOUND= User is already registered with this email