spring.application.name=job-portal-backend
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=job_portal
spring.data.mongodb.auto-index-creation=true
#Email Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

frontend.url=${FRONTEND_URL}
USER_FOUND= User is already registered with this email
USER_NOT_FOUND= User is not registered
INCORRECT_CREDENTIALS=Invalid Credentials
OTP_INCORRECT=OTP is incorrect
OTP_NOT_FOUND=OTP expired
PROFILE_NOT_FOUND=Profile not created